### ISSUE TITLE
Ability to "Back My Stack" with an anonymous profile

### ISSUE THREAD

**Issue by znarf** [opencollective/backyourstack#182]
### Story

As anonymous user, I want to upload my dependency files and "Back My Stack" using the special Open Collective Tier.

### Scenario

1. Go on https://backyourstack.com/
2. Upload a first dependency file, ie: https://raw.githubusercontent.com/opencollective/opencollective-frontend/master/package.json
3. Upload a first dependency file, ie: https://raw.githubusercontent.com/opencollective/opencollective-api/master/package.json
4. Click on a "Save Profile" button
 - The files will be persisted to s3 under a randomly generated identifier, ie: `Pi9vF3knlTIwKcFtmBvzX4NHGmAfbeNr`
 - The `backing.json`will be available at https://backyourstack.com/Pi9vF3knlTIwKcFtmBvzX4NHGmAfbeNr/backing.json
5. Click on a "Back My Stack" button
6. A confirmation page will explain in plain english what "Backing My Stack" means, the main action is a button that
redirect to http://staging.opencollective.com/backyourstack2/contribute/level-1-9912/checkout?data={%22jsonUrl%22:%22http:\/\/backyourstack.com\/Pi9vF3knlTIwKcFtmBvzX4NHGmAfbeNr\/backing.json%22}
6. On success from the Open Collective flow, I'm redirected on a BackYourStack page confirming what happened and what I can do next

**Comment by flickz** [comment]
> Click on a "Save Profile" button

Where does this "Save Profile" appear?

Below the "Drag and drop" on the home page 
![Screenshot from 2019-07-04 11-22-56](https://user-images.githubusercontent.com/15707013/60659901-70e1e180-9e4e-11e9-89f6-68b11d28f1c9.png)

Or on the files page
![Screenshot from 2019-07-04 11-23-26](https://user-images.githubusercontent.com/15707013/60659988-a2f34380-9e4e-11e9-88eb-f344f232ff87.png)

**Comment by flickz** [comment]
Closed in https://github.com/opencollective/backyourstack/pull/194
