### ISSUE TITLE
show when a company is already backing a project

### ISSUE THREAD

**Issue by piamancini** [opencollective/backyourstack#19]
from Dan Abramov: 

> It could be something simple like a checkmark or something on the badge
> like "this org already backs this project"
>  otherwise how does one measure "progress"?
> I have to squint to see that facebook is already supporting babel and people will run the big names to see how they are doing. 
>

**Comment by piamancini** [comment]
same comment made by Joe Lencioni form airbnb:  

> On this page https://backyourstack.now.sh/airbnb I think it would be nice to highlight somehow projects that are already backed by the organization. Maybe a little badge or something, or make sure it always shows up in the list of backers.

**Comment by znarf** [comment]
Done!
