### ISSUE TITLE
Mockups - Design

### ISSUE THREAD

**Issue by xdamman** [opencollective/backyourstack#2]
# Homepage

![](https://cl.ly/02330d3s0T2q/Screen%20Shot%202018-06-13%20at%203.59.54%20PM.png)

# Report page
![](https://cl.ly/2q0r1C2I033e/Screen%20Shot%202018-06-13%20at%204.01.43%20PM.png)

**Comment by piamancini** [comment]
First impressions: 
- If we want to do this a non OC driven website (and I think that's a good idea) I would remove the top backers from the homepage. Unless we are prepared to add how much Google is contributing to Node Foundation for example, we shouldn't just have the OC leaderboard there. 

- The report page is very cluttered. We don't need to replicate all the features on the collective, they can go there to see them. The sponsor cards and the goals only add noise. I one line with the Open Collective sponsors (like we did in the CLI)  is enough to give an idea of who and how much companies are giving. 

- The best way to put this to go viral is imho is to do one thing - and one thing only right: for anyone to check a company's dependencies, see which ones have collectives and click to contribute. I imagine something as simple the google front page for the input and a very simple report almost like the CLI output. We can build on that later on.  We can add a link to create a collective and a contact email, but I wouldn't have much else.

**Comment by cuiki** [comment]
Hi @piamancini, can you post an example of the CLI? I don't what you're referring to.

**Comment by xdamman** [comment]
Ok for removing the top backers.

The idea of showing more information was to make it more like a report that can almost be printed or at least sent by email. People won’t click on more than one collective to find out more.

They should have all the information at a glance: we are relying on the work of 30 open source projects, 10 of them need financial super (not all of them need support and that’s fine), right now they are sponsored by x y and z (and they each put $a $b and $c) and they need that much to reach their next financial goal.

That said I agree that the mock-up above is cluttered. I’m not a designer. I’m sure @cuiki can make this less cluttered. Apply your magic! :-)

**Comment by xdamman** [comment]
@cuiki those would be links to static pages. Maybe even to the wiki to start. 

Here is an example of the CLI that Pia was referring to: https://twitter.com/opencollect/status/1004393250164301824?s=21

**Comment by piamancini** [comment]
@cuiki I like the homepage's simplicity, that works great. 

I'm not a fan of the logo, specially the emoji.  It also looks like you are using [OSI's logo](https://opensource.org/) and while it's normally confused with an 'open source' logo, it's their institutional one.

**Comment by cuiki** [comment]
Oh, I didn't realize that it was institutional. Yes, I was under the impression that it was a public-domain symbol for 'open source'.

I just removed it.

**Comment by cuiki** [comment]
The InVision link is a clickable prototype. Also the tablet + smartphone view has been added.

We'll focus on the logo after the page is done. :)

**Comment by piamancini** [comment]
@cuiki I can't see the other views. do you mean the arrow on the right?

**Comment by cuiki** [comment]
Screens:

![homepage - default xl l m](https://user-images.githubusercontent.com/981188/41430822-bad32936-6fd6-11e8-9092-60635c6ce155.jpg)
![loading xl l m](https://user-images.githubusercontent.com/981188/41430825-bae95c42-6fd6-11e8-8eb4-8693d4dac205.jpg)

**Comment by xdamman** [comment]
I think we should a drop zone on the homepage to also give the option to people to drag and drop or select a/multiple package.json files. 
Sorry I should have thought about that in the mock-up.

**Comment by cuiki** [comment]
So is this an alternative way for people that may not be on GH?

**Comment by xdamman** [comment]
Most companies have private repos that are not public and most employees won't feel comfortable to give us access to them. So we need to give them a safe way to upload their `package.json` files.

**Comment by cuiki** [comment]
Hi. Here's an update for the report page: https://invis.io/FXLB4WOHJVZ#/303879404_Report_-_Default_-XL-_L-_M-

I left some comments to explain my thinking. It is not finished yet. I need to do the top part that includes the notification and the side information in the wireframe.

**Comment by piamancini** [comment]
I like it. 
I left a comment there too, related to my initial comment above.

**Comment by cuiki** [comment]
An update for the report page is available: https://invis.io/R5LM861KC6W#/303879404_Report_-_Default_-XL-_L-_M-

I also updated the homepage with the file upload, including responsive views, but I need to work on the state when a file(s) is(are) uploaded. I also updated the report page with the past feedback applied. I had a few questions though that came from seeing https://backyourstack.now.sh/ and that I wasn’t sure if I should follow what is shown in those states. I already flushed them out with @zarf and will add the stuff from the prototype in the mocks.

The report cards were tightened up a bit so they take less space than before and will solve the list of the other dependencies in a different way, as per what I spoke with François.

**Comment by cuiki** [comment]
The InVision prototype for Back you Stack has a few updates: https://invis.io/R5LM861KC6W#/303879404_Report_-_Default_-XL-_L-_M-

› Error validation for file upload.
› Logged in state for GH account (including hover on the top right to show the organizations and to sign out.)
› Moved the notification of a public search to the top per @xdamman feedback.
› Auto-complete for public GitHub repos search.
› After clicking a result in the auto-complete, you see the loading screen and after 1,200 ms it takes you to the report-page.

**Comment by cuiki** [comment]
Another update: https://invis.io/R5LM861KC6W#/303879404_Report_-_Default_-XL-_L-_M-

› Updated the prototype flow. You can "log-in" and "log-out" in the report page 
› New layout for report page.
- Removed the sponsors from the cards and placed them on the left sidebar
- Added tabs for viewing the rest of the dependencies and the repositories of the report.
- The open source projects cards were reduced in size a bit and placed in a grid.
› You can close the notification bar.

**Comment by cuiki** [comment]
Hi @znarf , I made some updates last night to the prototype.

› Show a report page based on uploaded files.
› Some minor changes to the general UI.

I saw you sent me a message in Slack but it is down and I can't read it. Can you tel me here?

**Comment by znarf** [comment]
"would be great to quickly design the Login intermediary page. And to have your feedback on the Upload handling now that you get how it’s working."

**Comment by znarf** [comment]
Latest version: https://backyourstack-lzsinysmrm.now.sh/f

**Comment by cuiki** [comment]
Latest update:

› Oauth screen is done: https://invis.io/NEM2AP1295M#/305846073_authenticate_Gh_Account
› Styles for buttons and drop-zone: https://invis.io/X6M2B4387TE#/305838494_button-Styles
› Files to customize avatars and covers for open collectives: https://www.dropbox.com/sh/2rh6fr9i3qmp865/AADxrte-u3CAY3qST7FcmDyja?dl=0

I had uploaded them to OC's Dropbox. I'm constantly doing one or two of these every couple of days to help them look better.

**Comment by cuiki** [comment]
Update:

› Here is the badge for collectives that are already supported in a stack: https://tafka.d.pr/Dq9U08
  (I changed the button to "Update Contribution" to still have an opportunity to hopefully increase the support from a sponsor who is already backing the open collective.) Also on InVision but if there is any issue @znarf, the graphic is attached here as well.
![badge 2x](https://user-images.githubusercontent.com/981188/42286106-576057ec-7f77-11e8-900d-6d767f3addc0.png)

› The mocks reflect the Share on Linked button as well.

**Comment by xdamman** [comment]
I like the badge but not sure about changing the color of the logo.

To make things easier, it would be great if you could post a screenshot
here of the end result. Assets can be kept in invision.

**Comment by piamancini** [comment]
I like the badge too. It's friendlier than adding the amount of money contributed.

**Comment by cuiki** [comment]
Sure @xdamman, the end was in a link but here is a direct screen.

![card badge](https://user-images.githubusercontent.com/981188/42287601-94dd0bba-7f7c-11e8-8808-c50e0e31b75d.png)

**Comment by xdamman** [comment]
Great. Thanks. 
Not sure about the white button though. Feels almost like it cannot be pressed. Why not keeping the same color or slightly a different tone maybe?

**Comment by znarf** [comment]
What I don't like about "Update contribution" is that most of the visitors of a given page are not the administrators themselves but just random visitors.
