### ISSUE TITLE
clarify why you need to  sign w github

### ISSUE THREAD

**Issue by piamancini** [opencollective/backyourstack#22]

**Comment by piamancini** [comment]
add a legend that signing up w github surfaces private repositories on your organization

someone else just made the same feedback comment 
> [ sign in with GitHub ] => [ sign in with GitHub to add private repositories ] (super long but maybe worth it otherwise I did not get it)

**Comment by cuiki** [comment]
I'm not so sure how to tackle this one. That button label is too long. Maybe an on-boarding bubble or top notification?

**Comment by piamancini** [comment]
@cuiki we are living it for now, only focusing on the ones tagged v1

**Comment by znarf** [comment]
For me, the text on the Sign In page and in the FAQ is enough.

Maybe what we need is change the UX and remove the "Sign in with Github" altogether.
