### ISSUE TITLE
Improve 'BackMyStack' first dispatch.

### ISSUE THREAD

**Issue by flickz** [opencollective/backyourstack#247]
Currently in our first dispatch, we're repeating the process of fetching recommended collectives on opencollective api by calling the `backing.json` api endpoint again.

We already have the recommended collectives for first dispatch we shouldn't call that endpoint to reanalyze and fetch them again as this takes significant amount of time leading to intermittent failure with dispatch.

**Comment by znarf** [comment]
Let's forget about this solution.

I recommend to address the root issue and to stop trying to do the dispatch synchronously.

When redirected to BackYourStack:

- we can display a simple confirmation message without the details. say that the dispatch will be happening and they will get a confirmation email
- the dispatch GraphQL mutation should just answer "ok", and process the dispatch in the background (this behavior can be turned on with an option asynchronous/synchronous)
- the dispatch process should send a confirmation email to the admins of the donating collective, this should contain the details that where earlier in the confirmation screen.
