### ISSUE TITLE
improve footer to clarify who started it

### ISSUE THREAD

**Issue by piamancini** [opencollective/backyourstack#29]
This is an open source project started by Open Collective - Contribute! [link to a contribute.md]

**Comment by cuiki** [comment]
The footer's new text is now updated in InVision.

**Comment by znarf** [comment]
So: "Back your Stack is an open source project started by Open Collective"?

My take: "Back your Stack is an open source project initiated by Open Collective"

**Comment by znarf** [comment]
Commited in: https://github.com/opencollective/backyourstack/commit/b92bc3331416fbdfdac5edd881634f1ea8a9bfbc

Let me know if you want to tweak it.
