### ISSUE TITLE
fix twitter share

### ISSUE THREAD

**Issue by piamancini** [opencollective/backyourstack#43]
it includes a twitter link in the tweet
<img width="755" alt="screen shot 2018-07-13 at 5 25 01 pm" src="https://user-images.githubusercontent.com/3671070/42699673-bb02f650-86c1-11e8-80bb-74cc7500f408.png">

**Comment by znarf** [comment]
Fixed in: https://github.com/opencollective/backyourstack/commit/d498238ba2214d6b72b7837b9fa4e89f5fe1092f
