### ISSUE TITLE
long org titles overlap with menu bar

### ISSUE THREAD

**Issue by piamancini** [opencollective/backyourstack#44]
<img width="1072" alt="screen shot 2018-07-13 at 5 26 15 pm" src="https://user-images.githubusercontent.com/3671070/42699730-e5053b48-86c1-11e8-8d13-6ee44c90e85e.png">

**Comment by alannallama** [comment]
Yep, I noticed the same thing.

<img width="954" alt="screen shot 2018-07-21 at 9 58 29 am" src="https://user-images.githubusercontent.com/5498878/43027354-e7959b16-8ccd-11e8-869f-a367dde1e772.png">

**Comment by znarf** [comment]
@piamancini @alannallama what do you think we should do?

**Comment by alannallama** [comment]
I'm not a designer, but if it were me I'd put some more vertical space between the line with the title and the line with the tab links, so it didn't overlap. @znarf

**Comment by znarf** [comment]
@cuiki what do you think?

**Comment by cuiki** [comment]
There are two things that we can do:

1. We can add a "..." after a certain number of characters (this is the easiest).
<img width="426" alt="screen shot 2018-07-24 at 8 08 39 am" src="https://user-images.githubusercontent.com/981188/43140059-cd3f1d4e-8f18-11e8-824e-655157414cf1.png">

2. There is another thing thats a bit more complicated which is to have different text templates for short and long names, example:
<img width="413" alt="screen shot 2018-07-24 at 8 07 39 am" src="https://user-images.githubusercontent.com/981188/43139952-ad19ee2c-8f18-11e8-9fce-1cea4e851d98.png">

**Comment by znarf** [comment]
@cuiki thank you for the input, I'll try these options.

**Comment by piamancini** [comment]
If it’s doable, the second option is preferable IMHO
