### ISSUE TITLE
Fix image for social media sharing

### ISSUE THREAD

**Issue by alannallama** [opencollective/backyourstack#45]
This is how it looks on Facebook:

<img width="513" alt="screen shot 2018-07-21 at 10 06 17 am" src="https://user-images.githubusercontent.com/5498878/43027396-19676cf0-8cce-11e8-98e8-7c6b3c78809e.png">

**Comment by znarf** [comment]
@cuiki Could you provide a logo suitable for Facebook sharing?

**Comment by cuiki** [comment]
This is the version of the logo within a squared image file:
![logo-bys-fb](https://user-images.githubusercontent.com/981188/43118175-48adf61e-8ed6-11e8-86e8-94ca8e2861fe.png)

I think this should work.

**Comment by znarf** [comment]
https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fbackyourstack.com%2F

![screen shot 2018-07-24 at 10 57 40](https://user-images.githubusercontent.com/806/43127733-7201524a-8f30-11e8-97b8-042eb54b5bb9.png)

Better?

**Comment by alannallama** [comment]
looks great!

**Comment by znarf** [comment]
Cool! Closing then.
