### ISSUE TITLE
Support for Go projects

### ISSUE THREAD

**Issue by caarlos0** [opencollective/backyourstack#75]
You could pretty much look the `.go` files and its import paths (would be like `github.com/user/repo/foo/bar` or something like that).

Other options are repos that have the vendor folder commited and also to look into Gopkg.lock, go.mod and etc... but I think that just `.go` files may be enough :) 

Great project btw 🚀

**Comment by znarf** [comment]
@caarlos0 Our current strategy is to focus on package managers files. So, looks like `Gopkg.toml` and/or `Gopkg.lock` are the way to go.

While our code is not Go, it should be relatively easy to implement so feel free to have a look and contribute! It's just a matter of detecting the files and transforming it in a common structure.

**Comment by znarf** [comment]
Closing, thank you @caarlos0!

**Comment by caarlos0** [comment]
Thanks!
